name: vidhyatri
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # core
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.3.4
  logger: ^2.0.2+1
  sandbox_logger: ^2.1.0
  google_nav_bar: ^5.0.6
  rxdart: ^0.27.7

  # local to global
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  firebase_ui_localizations: ^1.10.2
  equatable: ^2.0.5
  hive: ^2.2.3
  path_provider: ^2.1.2

  #firebase
  firebase_auth: ^4.17.0
  firebase_core: ^2.8.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.7
  cloud_firestore: ^4.15.6
  firebase_analytics: ^10.8.7
  firebase_crashlytics: ^3.4.16

  # Theme
  flex_color_scheme: ^7.3.1
  flex_seed_scheme: ^1.4.0
  flex_color_picker: ^3.3.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.4
  firebase_ui_auth: ^1.13.0
  firebase_ui_oauth_google: ^1.3.0
  firebase_ui_firestore: ^1.6.2
  firebase_ui_shared: ^1.4.1
  google_fonts: ^5.1.0

  hive_flutter: ^1.1.0

  image_picker: ^1.0.7
  google_ml_kit: ^0.16.3

  url_launcher: ^6.1.12
  string_scanner: ^1.2.0
  flutter_onboarding_slider: ^1.0.11
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  # a tool for running code generators
  build_runner: ^2.4.8
  # the code generator
  riverpod_generator: ^2.3.11
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.3.9
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.6.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    # Google fonts, font assets
    - assets/google_fonts/
  # Custom icon font package with only needed and used icons.
  fonts:
    - family: FlexIcons
      fonts:
        - asset: assets/fonts/FlexIcons.ttf
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mylogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/mylogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/mylogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/mylogo.png"
